### ISSUE TITLE
For texture tilestyle="none": define a border color

### ISSUE THREAD

**Issue by KrisIverson** [3MFConsortium/spec_materials#10]
Current specification says to use the default object color when a texture tilestyle is none. The way it’s specified now it’s not particularly useful. Suppose we wanted to put a multi-property “sticker” on top of object’s surface. The surface itself might be textured, translucent, etc. but the specification forces us to use object’s default color in the second layer, in areas outside sticker…

We instead recommend adding a border color attribute and defining a fixed default when unspecified.

For example: When the texture is used in other than the base layer of multi-property material, the border color is #FFFFFF00, i.e. fully transparent. RGB is white in order not to modify the color in border areas when blending in multiply mode.

Adding a border_color attribute would allow us to do many things with border being transparent etc.

3D Builder will use white as border color when tilestyle="none" in the next update which is not what is defined in the current specification.

**Comment by jordig100** [comment]
Hi Kris, looking at your proposal, currently the color applied to tilestyle=none is the default object color.
Having a fixed default color in the schema would change this backwards compatibility, which it is being used by HP and I think that Materialise.
Would it be acceptable to have something like:
**bordercolor** - It specifies the border color in conjunction with the tile style of "none" to define the color to assign outside of the range zero to one.  If border color is not specified, it will be assigned the default object color. If neither is specified, the choice for the color is left to the consumer.

**Comment by jordig100** [comment]
Take a look at: https://github.com/3MFConsortium/spec_materials/blob/1.2.1-updates/3MF%20Materials%20Extension.md

**Comment by KrisIverson** [comment]
We are wondering if tilestyle=”none” is used by others? We feel it may have little practical use and likely no one is using it beyond inclusion in the 3MF test suite. It seems that using “clamp” is a better alternative with carefully crafted textures (transparent border area). This is how it is often done in game rendering. There is some debate in my team about the benefit of tilestyle=”none” and that maybe bordercolor attribute isn’t needed either. We’d like to know more about how others are thinking about it.

**Comment by martinweismann** [comment]
Fixed in https://github.com/3MFConsortium/spec_materials/releases/tag/1.2.1 .
